PCI = int(input("Enter PCI Marks"))
WPD = int(input("Enter WPD Marks"))
CPH = int(input("Enter CPH Marks"))
BCC = int(input("Enter BCC Marks"))
BEC = int(input("Enter BEC Marks"))
EEC = int(input("Enter EEC Marks"))
All = PCI+WPD+CPH+BCC+BEC+EEC
print("Your Total marks = ",All)
print("Your Percentage = ",(All/6))